<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Microsoft.Bcl.TimeProvider" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Options" Version="10.0.12" />
    <PackageVersion Include="System.Memory.Data" Version="10.0.12" />
    <PackageVersion Include="System.Threading.Channels" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <PackageVersion Include="MessagePack" Version="3.1.10" />
    <PackageVersion Include="Microsoft.IO.RecyclableMemoryStream" Version="3.0.1" />
    <PackageVersion Include="Polyfill" Version="11.4.1" />
  </ItemGroup>

  <ItemGroup>
    <GlobalPackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="18.7.23" />
    <GlobalPackageReference Include="Roslynator.Analyzers" Version="5.0.0" />
  </ItemGroup>

</Project>
