name: Build

on: [push, pull_request]

permissions:
  contents: read

jobs:

  build:
    name: Build
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'
        dotnet-quality: 'ga'

    - name: Restore dependencies
      run: dotnet restore

    - name: Check code formatting
      run: dotnet format --no-restore --verify-no-changes

    - name: Build
      run: dotnet build --no-restore

    - name: Run tests
      run: dotnet test --output Detailed --no-build --no-progress --max-parallel-test-modules 1 --results-directory "artifacts/testresults"

    - name: Upload Test Report (net10.0)
      uses: actions/upload-artifact@v7
      if: always()
      with:
        archive: false
        path: 'artifacts/testresults/TinyIpc.Tests-windows-net10.0-report.html'

    - name: Upload Test Report (net8.0)
      uses: actions/upload-artifact@v7
      if: always()
      with:
        archive: false
        path: 'artifacts/testresults/TinyIpc.Tests-windows-net8.0-report.html'

    - name: Upload Test Report (net48)
      uses: actions/upload-artifact@v7
      if: always()
      with:
        archive: false
        path: 'artifacts/testresults/TinyIpc.Tests-windows-net48-report.html'
